apiVersion: apps/v1
kind: Deployment
metadata:
  name: tellus-deployment
  labels:
    app: tellus
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: tellus
  template:
    metadata:
      labels:
        app: tellus
    spec:
      containers:
        - name: tellus
          image: tennander/tellus
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: webhook
          volumeMounts:
            - mountPath: /certs
              name: cert-key
            - mountPath: /config
              name: config
      volumes:
        - name: cert-key
          secret:
            secretName: github-app-key
        - name: config
          configMap:
            name: tellus-config

---
apiVersion: v1
kind: Service
metadata:
  name: tellus-service
  labels:
    app: tellus
spec:
  type: NodePort
  selector:
    app: tellus
  ports:
    - port: 8080
      targetPort: webhook
      nodePort: 31010
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tellus-config
  labels:
    app: tellus
data:
  tellus.yml: |
    repositoryRootDirectory: /repos/
    webPort: 8080
    github:
      privateKey:
        location: /certs/key.pem
      integrationId: 27253
      installationId: 764001